require("taiwork.plugins-setup")
require("taiwork.core.options")
require("taiwork.core.keymaps")
require("taiwork.core.colorscheme")
require("taiwork.plugins.comment")
require("taiwork.plugins.nvim-tree")
require("taiwork.plugins.lualine")
require("taiwork.plugins.telescope")
require("taiwork.plugins.nvim-cmp")
require("taiwork.plugins.lsp.mason")
require("taiwork.plugins.lsp.lspsaga")
require("taiwork.plugins.lsp.lspconfig")
require("taiwork.plugins.lsp.null-ls")
require("taiwork.plugins.autopairs")
require("taiwork.plugins.treesitter")
require("taiwork.plugins.gitsigns")

-- original
require("taiwork.plugins.auto-session")
require("taiwork.plugins.copilot")
